"""The rule table: what each command is, and how much it costs to be wrong.

Read top to bottom as a catalogue. Every entry is one R(...) call."""

from __future__ import annotations

from .catalog import R



READ_ONLY = (
    "ls cat echo pwd whoami id date uname df du free ps top htop grep egrep fgrep awk head tail "
    "wc sort uniq which type file stat printenv hostname dig nslookup host whois ping traceroute "
    "mtr netstat ss lsof uptime env true false sleep tree jq yq column tee less more diff cmp "
    "md5sum sha256sum base64 seq basename dirname realpath readlink getent locale tty arch nproc"
)

# CLIs that manage resources somewhere else — cloud, SaaS, storage, virt.
# Their verbs are consistent enough to classify generically, which is what
# keeps a CLI nobody has written a rule for from scoring "safe".
RESOURCE_CLIS = (
    "hcloud scw doctl linode-cli lin vultr-cli exo civo upcloud ibmcloud oci aliyun ovhai "
    "flyctl fly heroku railway vercel netlify wrangler render pscale supabase planetscale "
    "gh glab tea eksctl velero argocd flux linkerd istioctl virsh incus lxc machinectl "
    "s3cmd rclone restic borg etcdctl vault consul nomad pulumi cdk cdktf serverless sls "
    "openstack ionosctl hetzner-k3s stripe twilio fastly akamai cf snap zfs ceph rbd"
)
# Verb position matters: the first verb in the command wins, so a resource
# *named* delete-me does not turn a describe into a destroy.
_LEAD = r"(?:\S+[\s:]){0,3}"
_READ = r"(?:list|ls|describe|get|show|info|status|version|inspect|read|view|search|find|diff)"
READ_VERBS = rf"^{_LEAD}{_READ}\b"
WRITE_VERBS = (
    rf"^(?!{_LEAD}{_READ}\b){_LEAD}"
    r"(?:create|add|new|update|set|attach|enable|apply|deploy|scale|resize|restart|"
    r"import|upload|put|publish|promote|rename|label|tag)\b"
)
DESTROY_VERBS = (
    rf"^(?!{_LEAD}{_READ}\b){_LEAD}"
    r"(?:delete|destroy|remove|rm|terminate|purge|prune|wipe|revoke|disable|detach|"
    r"drop|kill|reset|teardown|down|deprovision|decommission|expire)\b"
)

RULES = [
    # --- read-only baseline -------------------------------------------------
    R("READ", READ_ONLY, None, 0, "none", "reversible", "read-only: inspects, changes nothing"),
    R(
        "READ-BUILTIN",
        "set cd export alias local declare readonly shift trap pushd popd dirs "
        "umask ulimit test [ time getopts read printf let",
        None,
        0,
        "none",
        "reversible",
        "shell builtin: affects this shell only",
    ),
    R(
        "READ-KEYWORD",
        "if then else elif fi for while until do done case esac in function select break continue return exit",
        None,
        0,
        "none",
        "reversible",
        "shell keyword: control flow, not a command",
    ),
    R("READ-SED", "sed", None, 0, "none", "reversible", "stream edit to stdout, no file touched"),
    R(
        "FS-SED-I",
        "sed perl",
        r"(^|\s)-i",
        35,
        "file",
        "irreversible",
        "in-place edit: the original is overwritten unless a backup suffix is given",
        "`sed -i.bak` keeps the original next to the edited file",
        paths=True,
    ),
    R("READ-FIND", "find", None, 0, "none", "reversible", "directory walk, no mutation"),
    R(
        "READ-CURL",
        "curl wget",
        None,
        5,
        "none",
        "reversible",
        "network fetch; harmless until the response is executed or written",
    ),
    R(
        "READ-SSH",
        "ssh",
        None,
        10,
        "host",
        "reversible",
        "opens a session on another host; risk is whatever runs there",
    ),
    # --- filesystem ---------------------------------------------------------
    R(
        "FS-RM",
        "rm",
        None,
        35,
        "file",
        "irreversible",
        "rm unlinks immediately: no trash, no undo",
        "`rm -i`, or move to a staging dir and delete it later",
    ),
    R("FS-RMDIR", "rmdir unlink", None, 20, "file", "irreversible", "removes a directory entry"),
    R(
        "FS-SHRED",
        "shred wipe",
        None,
        55,
        "file",
        "irreversible",
        "overwrites the data before unlinking: undelete tools cannot help",
    ),
    R(
        "FS-MV",
        "mv",
        None,
        25,
        "file",
        "recoverable",
        "moves/overwrites; a destination that exists is silently replaced",
        "`mv -n` refuses to clobber an existing destination",
    ),
    R(
        "FS-CP",
        "cp rsync install",
        None,
        20,
        "file",
        "recoverable",
        "writes over the destination tree",
    ),
    R("FS-TRUNCATE", "truncate", None, 45, "file", "irreversible", "resizes a file in place"),
    R(
        "FS-DD",
        "dd",
        None,
        45,
        "file",
        "irreversible",
        "raw block writes, no filesystem safety net",
        "double-check `of=`; `status=progress` will not save you from the wrong device",
    ),
    R(
        "FS-MKFS",
        "mkfs mkfs.ext4 mkfs.xfs mkfs.btrfs mkswap wipefs sgdisk fdisk parted cfdisk gdisk",
        None,
        85,
        "host",
        "irreversible",
        "formats or repartitions a device: every filesystem on it is gone",
        "verify with `lsblk -f` first; unmount and take an image if the data matters",
    ),
    R(
        "FS-MOUNT",
        "mount",
        None,
        15,
        "host",
        "reversible",
        "makes a filesystem visible: additive, and undone by unmounting it again",
    ),
    R(
        "FS-REMOUNT-RO",
        "mount",
        r"remount.*(^|[,\s])ro([,\s]|$)|(^|[,\s])ro([,\s]|$).*remount",
        45,
        "host",
        "recoverable",
        "remounting read-only: every writer on that filesystem starts failing immediately, "
        "usually as corruption-looking errors rather than a clean stop",
    ),
    R(
        "FS-UMOUNT",
        "umount",
        None,
        35,
        "host",
        "recoverable",
        "detaches a filesystem; every process holding a file under it breaks",
        "`fuser -m <path>` or `lsof +D <path>` shows who is using it first",
    ),
    R("FS-CHATTR", "chattr", None, 30, "file", "reversible", "changes immutable/append-only bits"),
    # --- permissions & privilege -------------------------------------------
    R(
        "PRIV-CHMOD",
        "chmod",
        None,
        25,
        "file",
        "reversible",
        "changes access bits; over-permissive modes are a security finding",
    ),
    R(
        "PRIV-CHOWN",
        "chown chgrp",
        None,
        30,
        "file",
        "recoverable",
        "changes ownership; services fail when they can no longer read their own files",
    ),
    R(
        "PRIV-USERDEL",
        "userdel groupdel deluser delgroup",
        None,
        55,
        "host",
        "irreversible",
        "removes an account; `-r` takes the home directory with it",
    ),
    R(
        "PRIV-PASSWD",
        "passwd chpasswd usermod",
        None,
        40,
        "host",
        "recoverable",
        "changes credentials; locking the wrong account ends your access",
    ),
    R("PRIV-VISUDO", "visudo", None, 35, "host", "recoverable", "edits sudo policy"),
    # --- shell / execution --------------------------------------------------
    R(
        "EXEC-EVAL",
        "eval",
        None,
        60,
        "host",
        "irreversible",
        "eval runs text assembled at run time: what executes cannot be read from this line, by "
        "you or by any reviewer, and if any part of that text came from outside the script it is "
        "arbitrary code execution",
        "there is almost always a direct form — arrays, `${!name}` indirection or a case "
        "statement — that says what it runs; if eval is truly needed, echo the string first",
    ),
    R(
        "EXEC-SOURCE",
        "source .",
        None,
        35,
        "host",
        "recoverable",
        "runs another file's commands in this shell, so it can also change this shell's environment and functions",
    ),
    R(
        "EXEC-SHELL",
        "sh bash zsh dash ksh",
        None,
        10,
        "host",
        "reversible",
        "spawns a shell; risk is whatever it is told to run",
    ),
    R("EXEC-FORKBOMB", "", None, 0, "none", "reversible", "placeholder"),
    R(
        "EXEC-HISTORY",
        "history",
        r"-c|-d",
        40,
        "host",
        "irreversible",
        "erases shell history: destroys the record of what was run",
        "if this is not deliberate audit-trail removal, do not run it",
    ),
    # --- system state -------------------------------------------------------
    R(
        "SYS-POWER-CTL",
        "systemctl",
        r"^(poweroff|reboot|halt|emergency|rescue|kexec|isolate)\b",
        70,
        "host",
        "recoverable",
        "takes the host down or into a target with almost nothing running",
    ),
    R(
        "SYS-POWER-CANCEL",
        "shutdown",
        r"(^|\s)-c(\s|$)",
        0,
        "none",
        "reversible",
        "cancels a pending shutdown: this is the undo, not the action",
    ),
    R(
        "SYS-POWER",
        "reboot shutdown halt poweroff",
        None,
        70,
        "host",
        "recoverable",
        "takes the host down; remote hosts may not come back without console access",
        "check for other sessions (`who`) and confirm out-of-band access first",
    ),
    R(
        "SYS-INIT",
        "init telinit",
        r"^[06]",
        70,
        "host",
        "recoverable",
        "changes runlevel: halt/reboot",
    ),
    R(
        "SYS-KILL",
        "kill pkill killall",
        None,
        35,
        "host",
        "recoverable",
        "terminates processes; `-9` gives them no chance to flush state",
    ),
    R(
        "SYS-SYSTEMCTL-R",
        "systemctl service",
        r"^(status|show|list-|is-|cat|get-default)",
        0,
        "none",
        "reversible",
        "read-only service query",
    ),
    R(
        "SYS-SYSTEMCTL-W",
        "systemctl service",
        r"^(restart|reload|start|enable|daemon-reload|daemon-reexec|set-property|edit)\b",
        25,
        "host",
        "recoverable",
        "changes service state; a restart is a brief outage, and a config that no longer parses will not come back up",
    ),
    R(
        "SYS-SYSTEMCTL",
        "systemctl service",
        r"^(stop|disable|kill)",
        45,
        "host",
        "recoverable",
        "stops a service; anything depending on it fails now",
    ),
    R(
        "SYS-MASK",
        "systemctl",
        r"^mask",
        55,
        "host",
        "recoverable",
        "masking hides the unit entirely: later `start` silently does nothing",
    ),
    R(
        "SYS-CRONTAB",
        "crontab",
        r"(^|\s)-r(\s|$)",
        60,
        "host",
        "irreversible",
        "`crontab -r` deletes the whole crontab with no confirmation (and sits next to `-e`)",
        "`crontab -l > backup.cron` first — always",
    ),
    R(
        "SYS-SWAP",
        "swapoff",
        None,
        30,
        "host",
        "reversible",
        "disables swap; can trigger the OOM killer",
    ),
    R(
        "SYS-SYSCTL",
        "sysctl",
        r"-w|=",
        35,
        "host",
        "reversible",
        "changes kernel parameters at runtime",
    ),
    # --- network ------------------------------------------------------------
    R(
        "NET-IFUP",
        "ifup",
        None,
        10,
        "network",
        "reversible",
        "brings an interface up: additive, and reversible from the same session",
    ),
    R(
        "NET-IFDOWN",
        "ifdown",
        None,
        50,
        "network",
        "recoverable",
        "brings an interface down: if it carries your session, you lose the host "
        "and the command that would bring it back",
        "wrap it: `(ifdown eth0; sleep 60; ifup eth0) &` — or use a console",
    ),
    R(
        "NET-IPLINK",
        "ip",
        r"^link\s+set\b.*\bdown\b",
        50,
        "network",
        "recoverable",
        "downs a link; same lockout risk as ifdown",
    ),
    R(
        "NET-IPREAD",
        "ip",
        r"^\w+\s+(show|list|get)|^(a|addr|link|route|neigh)$",
        0,
        "none",
        "reversible",
        "read-only network query",
    ),
    R(
        "NET-IPROUTE",
        "ip route",
        r"^(a|addr|address|route|r|rule|neigh|link|l)\s+(del|delete|flush|change|replace)|"
        r"^(del|delete|flush)\b",
        45,
        "network",
        "recoverable",
        "rewrites addressing or routing: the path your session is on may be one of them",
    ),
    R(
        "NET-NMCLI",
        "nmcli",
        r"^(c|con|connection)\s+(delete|down)|^(d|dev|device)\s+disconnect",
        50,
        "network",
        "recoverable",
        "takes down or deletes a NetworkManager connection: same lockout risk as ifdown",
    ),
    R(
        "NET-IPTABLES",
        "iptables ip6tables nft",
        r"-F|--flush|flush",
        65,
        "network",
        "recoverable",
        "flushing rules drops every allow rule too; with a DROP policy the host goes silent",
        "`iptables-save > rules.bak` first, and use a rollback timer",
    ),
    R(
        "NET-IPTABLES-P",
        "iptables ip6tables",
        r"-P\s+INPUT\s+DROP",
        75,
        "network",
        "recoverable",
        "sets the default input policy to DROP: immediate lockout unless SSH is already allowed",
    ),
    R(
        "NET-UFW",
        "ufw firewall-cmd",
        r"^(disable|reset|--force reset)|--remove-(service|port|source)|--set-target=DROP",
        45,
        "network",
        "recoverable",
        "removes or narrows host firewalling — including, possibly, the rule that lets you back in",
    ),
    R(
        "NET-NC",
        "nc ncat netcat",
        r"-e|-c",
        60,
        "network",
        "irreversible",
        "`nc -e` hands a shell to whatever is on the other end",
    ),
    R(
        "NET-TC",
        "tc",
        r"\bdel\b|\badd\b",
        40,
        "network",
        "recoverable",
        "traffic control changes affect every flow on the interface",
    ),
    # --- packages -----------------------------------------------------------
    # Installing is not a read: maintainer scripts run as root, and removals
    # take dependants and config with them.
    R(
        "PKG-READ",
        "apt apt-get aptitude yum dnf apk zypper brew pacman pip pip3 pipx npm yarn "
        "pnpm gem cargo composer nix-env snap flatpak port conda mamba poetry uv",
        r"^(list|search|show|info|policy|update|why|deps|outdated|audit|view|ls)\b",
        5,
        "none",
        "reversible",
        "queries or refreshes package metadata",
    ),
    R(
        "PKG-READ-FLAG",
        "dpkg rpm",
        r"(^|\s)-[a-zA-Z]*[lLqsSV](\s|$)|--(list|query|verify)\b",
        0,
        "none",
        "reversible",
        "queries the package database",
    ),
    R(
        "PKG-INSTALL",
        "apt apt-get aptitude yum dnf apk zypper pacman brew pip pip3 pipx npm yarn "
        "pnpm gem cargo go composer nix-env emerge port snap flatpak conda mamba "
        "micromamba poetry uv",
        r"^(install|add|i|upgrade|update|reinstall|get|build|sync)\b|(^|\s)-S(\s|$)",
        35,
        "host",
        "recoverable",
        "installs code and runs its maintainer/post-install scripts as root: arbitrary "
        "code execution by design, from whoever owns that package today",
        "pin the version, and read what a new repo/tap actually ships before adding it",
    ),
    R(
        "PKG-REMOVE",
        "apt apt-get aptitude yum dnf apk zypper pacman brew pip pip3 pipx npm yarn "
        "pnpm gem cargo composer nix-env port conda mamba micromamba poetry uv "
        "flatpak snap",
        r"^(remove|purge|autoremove|uninstall|erase|del|delete|rm|unmerge|prune)\b",
        45,
        "host",
        "recoverable",
        "removes packages; purge/autoremove also take configuration and dependencies",
        "read the 'to be REMOVED' list — autoremove has uninstalled running kernels before",
    ),
    # Flag-style removal, per binary: one shared regex either misses `-Rns` or
    # reads `pacman -Qe` as a removal.
    R(
        "PKG-RM-PACMAN",
        "pacman yay paru",
        r"(^|\s)-[A-Za-z]*R",
        50,
        "host",
        "recoverable",
        "`-R` removes packages; `-Rns` also takes their configs and unused dependencies",
    ),
    R(
        "PKG-RM-DPKG",
        "dpkg",
        r"(^|\s)-[rP](\s|$)|--(remove|purge)\b",
        50,
        "host",
        "recoverable",
        "removes a package without consulting the dependency solver",
    ),
    R(
        "PKG-RM-RPM",
        "rpm",
        r"(^|\s)-e\b|--erase\b",
        50,
        "host",
        "recoverable",
        "`rpm -e` removes a package with no transaction to roll back",
    ),
    R(
        "PKG-RM-NIX",
        "nix-env",
        r"(^|\s)-e\b|--uninstall\b",
        45,
        "host",
        "recoverable",
        "removes a package from the profile (the generation is still there until GC)",
    ),
    R(
        "PKG-RM-EMERGE",
        "emerge",
        r"(^|\s)-C\b|--unmerge\b|--depclean\b",
        50,
        "host",
        "recoverable",
        "unmerges packages; `--depclean` decides for itself what is unused",
    ),
    R(
        "PKG-RELEASE-UPGRADE",
        "do-release-upgrade",
        None,
        55,
        "host",
        "recoverable",
        "distribution release upgrade: replaces the kernel, libc and init in one transaction",
        "snapshot or image the host first; this is the operation servers do not come back from",
    ),
    R(
        "PKG-DIST-UPGRADE",
        "apt apt-get do-release-upgrade dnf zypper pacman",
        r"^(full-upgrade|dist-upgrade|system-upgrade|dup)\b|(^|\s)-Syu",
        55,
        "host",
        "recoverable",
        "distribution upgrade: replaces the kernel, libc and init in one transaction",
        "snapshot or image the host first; this is the operation servers do not come back from",
    ),
    R(
        "PKG-GC",
        "nix-collect-garbage brew yum dnf pacman",
        r"^(cleanup|clean)\b|(^|\s)-(d|Scc)(\s|$)",
        40,
        "host",
        "irreversible",
        "garbage-collects package state; `nix-collect-garbage -d` deletes the older generations, "
        "which are the rollback targets",
    ),
    R(
        "PKG-FORCE",
        "dpkg rpm apt-get",
        r"--force|--nodeps|--allow-downgrades",
        55,
        "host",
        "recoverable",
        "overrides the package manager's own consistency checks",
        subsumes="FORCE",
    ),
    R(
        "PKG-RUN",
        "npm yarn pnpm",
        r"^(run|run-script|exec|dlx)\b",
        10,
        "host",
        "reversible",
        "runs a script defined in package.json",
    ),
    R(
        "RUN-MAKE",
        "make gmake just task mise",
        None,
        10,
        "host",
        "reversible",
        "runs a target defined in the project's build/task file",
    ),
    R(
        "PKG-PUBLISH",
        "npm cargo gem twine",
        r"^publish\b|^upload\b",
        60,
        "account",
        "irreversible",
        "publishes to a public registry: unpublish windows are short and versions are permanent",
        "`npm publish --dry-run` and check `files`/`.npmignore` for secrets first",
    ),
    # --- remote code --------------------------------------------------------
    R("SEC-PIPE-SHELL", "", None, 0, "none", "reversible", "placeholder"),
    # --- git ----------------------------------------------------------------
    R(
        "GIT-READ",
        "git",
        r"^(status|log|diff|show|branch$|remote|fetch|describe|blame|stash list)",
        0,
        "none",
        "reversible",
        "read-only git query",
    ),
    R("GIT-PUSH", "git", r"^push\b", 20, "network", "recoverable", "publishes commits"),
    R(
        "GIT-PUSH-F",
        "git",
        r"^push\b.*(--force(?!-with-lease)|(\s|^)-f\b)",
        55,
        "network",
        "irreversible",
        "force-push overwrites remote history; other clones diverge silently",
        "`--force-with-lease` refuses when the remote moved under you",
        subsumes="FORCE",
    ),
    R(
        "GIT-PUSH-DEL",
        "git",
        r"^push\b.*(--delete|\s:\w)",
        50,
        "network",
        "recoverable",
        "deletes a remote ref",
    ),
    R(
        "GIT-RESET",
        "git",
        r"^reset\b.*--hard",
        40,
        "directory",
        "irreversible",
        "discards uncommitted work in the tree and index",
        "`git stash -u` costs nothing and is undoable",
    ),
    R(
        "GIT-CLEAN",
        "git",
        r"^clean\b.*-[a-z]*[fd]",
        45,
        "directory",
        "irreversible",
        "deletes untracked files; `-x` also takes ignored ones (.env, local configs)",
        "`git clean -nd` prints what it would delete",
    ),
    R(
        "GIT-BRANCH-D",
        "git",
        r"^branch\b.*-D",
        25,
        "directory",
        "recoverable",
        "force-deletes a branch without a merge check (reflog keeps it for a while)",
    ),
    R(
        "GIT-REFLOG-EXPIRE",
        "git",
        r"^reflog\s+expire.*--expire[= ](now|all)|^gc\b.*--prune[= ]now",
        60,
        "directory",
        "irreversible",
        "the reflog is what makes `reset --hard` and a deleted branch recoverable; expiring it "
        "turns every earlier 'recoverable' into 'gone'",
    ),
    R(
        "GIT-PUSH-MIRROR",
        "git",
        r"^push\b.*--mirror",
        70,
        "network",
        "irreversible",
        "`--mirror` makes the remote match your local refs exactly: branches and tags you do "
        "not have locally are deleted on the remote",
    ),
    R(
        "GIT-STASH-CLEAR",
        "git",
        r"^stash\s+(clear|drop)",
        35,
        "directory",
        "irreversible",
        "stash entries are unreachable once dropped; only a reflog hunt finds them",
    ),
    R(
        "GIT-REWRITE",
        "git",
        r"^(filter-branch|filter-repo|rebase\b.*-i)",
        45,
        "directory",
        "recoverable",
        "rewrites history: every existing clone and PR is invalidated",
    ),
    R(
        "GIT-CHECKOUT-F",
        "git",
        r"^(checkout|restore|switch)\b.*(-f|--force|--hard)|^(checkout|restore)\s+\.(\s|$)",
        35,
        "directory",
        "irreversible",
        "overwrites local modifications",
    ),
    # --- containers ---------------------------------------------------------
    R(
        "CTR-READ",
        "docker podman nerdctl",
        r"^(ps|images|image ls|logs|inspect|stats|top|version|info|port|diff|history)\b",
        0,
        "none",
        "reversible",
        "read-only container query",
    ),
    R(
        "CTR-EXEC",
        "docker podman nerdctl kubectl",
        r"^exec\b",
        20,
        "container",
        "reversible",
        "runs a command inside a running container: scored on the payload below",
    ),
    R(
        "CTR-RUN",
        "docker podman nerdctl",
        r"^(run|create|start)\b",
        20,
        "container",
        "reversible",
        "starts a container: what actually runs is the image ENTRYPOINT/CMD unless overridden",
    ),
    R(
        "CTR-RM",
        "docker podman nerdctl",
        r"^(rm|rmi|image rm|container rm)\b",
        30,
        "container",
        "recoverable",
        "removes containers/images; anything not in a volume goes with them",
    ),
    R(
        "CTR-VOLUME-RM",
        "docker podman",
        r"^volume\s+(rm|prune)",
        60,
        "host",
        "irreversible",
        "volumes are where the data actually lives",
        "`docker run --rm -v vol:/v alpine tar cf - /v > vol.tar` before removing",
    ),
    R(
        "CTR-PRUNE",
        "docker podman",
        r"^(system|image|container|builder|network)\s+prune",
        45,
        "host",
        "irreversible",
        "prunes unused objects; `-a --volumes` interprets 'unused' very broadly",
    ),
    R(
        "CTR-COMPOSE-DOWN",
        "docker-compose",
        r"^down\b.*(-v|--volumes)",
        60,
        "host",
        "irreversible",
        "`down -v` deletes the stack's volumes: databases included",
        subsumes="PURGE-FLAG",
    ),
    R(
        "CTR-KILL",
        "docker podman",
        r"^(kill|stop|restart)\b",
        30,
        "container",
        "recoverable",
        "stops running containers",
    ),
    # --- kubernetes ---------------------------------------------------------
    R(
        "K8S-READ",
        "kubectl oc",
        r"^(get|describe|logs|top|explain|api-resources|api-versions|version|cluster-info|diff|"
        r"auth can-i|config (view|get|current))\b",
        0,
        "none",
        "reversible",
        "read-only cluster query",
    ),
    R(
        "K8S-APPLY",
        "kubectl oc",
        r"^(apply|create|replace|patch|edit|set|label|annotate)\b",
        30,
        "cluster",
        "recoverable",
        "mutates cluster state",
    ),
    R(
        "K8S-DELETE",
        "kubectl oc",
        r"^delete\b",
        55,
        "cluster",
        "irreversible",
        "deletes resources; controllers will not bring back what they did not create",
        "`--dry-run=server` first, and keep the manifest in git",
        generic=True,
    ),
    R(
        "K8S-DELETE-POD",
        "kubectl oc",
        r"^delete\s+(pod|pods|po)\b(?!.*(--all|--all-namespaces|(\s)-A(\s|$)))",
        25,
        "cluster",
        "recoverable",
        "a named pod is replaced by its controller — this is a restart, not a deletion",
    ),
    R(
        "K8S-DELETE-NS",
        "kubectl oc",
        r"^delete\b.*\b(ns|namespace)\b",
        80,
        "cluster",
        "irreversible",
        "deleting a namespace cascades to everything inside it, PVCs included",
        "there is no undo and no controller that will rebuild it — export the namespace first",
    ),
    R(
        "K8S-DELETE-CRD",
        "kubectl oc",
        r"^delete\b.*\b(crd|customresourcedefinition)",
        85,
        "cluster",
        "irreversible",
        "deleting a CRD deletes every custom resource of that kind, cluster-wide, in one go",
        "check `kubectl get <kind> -A` first — the cascade is invisible from this line",
    ),
    R(
        "K8S-DELETE-PVC",
        "kubectl oc",
        r"^delete\b.*\b(pvc|persistentvolumeclaim|pv)\b",
        75,
        "cluster",
        "irreversible",
        "PVCs are the data; with a Delete reclaim policy the underlying volume goes too",
    ),
    R(
        "K8S-DRAIN",
        "kubectl oc",
        r"^drain\b",
        50,
        "cluster",
        "recoverable",
        "evicts every pod from a node; PDBs are the only thing keeping this safe",
    ),
    R(
        "K8S-CORDON",
        "kubectl oc",
        r"^(cordon|uncordon|taint)\b",
        20,
        "cluster",
        "reversible",
        "changes node schedulability",
    ),
    R(
        "K8S-SCALE-0",
        "kubectl oc",
        r"^scale\b.*--replicas[= ]0\b",
        45,
        "cluster",
        "reversible",
        "scales to zero: an outage that looks like a config change",
    ),
    R(
        "K8S-ROLLOUT",
        "kubectl oc",
        r"^rollout\s+(restart|undo)",
        30,
        "cluster",
        "recoverable",
        "restarts or reverts a workload",
    ),
    R(
        "K8S-PF",
        "kubectl oc",
        r"^(port-forward|proxy)\b",
        15,
        "network",
        "reversible",
        "bridges cluster network into this host for as long as it runs",
    ),
    R(
        "HELM-READ",
        "helm",
        r"^(list|ls|status|get|show|history|template|diff|search)\b",
        0,
        "none",
        "reversible",
        "read-only release query",
    ),
    R(
        "HELM-INSTALL",
        "helm",
        r"^(install|upgrade)\b",
        35,
        "cluster",
        "recoverable",
        "applies a chart; `--force` recreates resources rather than patching them",
    ),
    R(
        "HELM-DELETE",
        "helm",
        r"^(uninstall|delete)\b",
        60,
        "cluster",
        "irreversible",
        "removes a release; PVCs created by the chart usually go too",
    ),
    # --- IaC ----------------------------------------------------------------
    R(
        "IAC-READ",
        "terraform tofu",
        r"^(plan|validate|fmt|show|output|providers|version|graph)\b",
        0,
        "none",
        "reversible",
        "read-only or planning operation",
    ),
    R(
        "IAC-APPLY",
        "terraform tofu",
        r"^apply\b",
        45,
        "account",
        "recoverable",
        "applies a plan to real infrastructure",
    ),
    R(
        "IAC-DESTROY",
        "terraform tofu",
        r"^destroy\b",
        80,
        "account",
        "irreversible",
        "destroys every resource in the state file",
        "`terraform plan -destroy` and check the workspace — this is how prod dies",
    ),
    R(
        "IAC-STATE-RM",
        "terraform tofu",
        r"^state\s+(rm|mv|push|replace-provider)",
        60,
        "account",
        "recoverable",
        "edits state directly: state and reality drift apart from here",
        "`terraform state pull > state.bak` first",
    ),
    R(
        "IAC-TAINT",
        "terraform tofu",
        r"^(taint|apply -replace|untaint)",
        40,
        "account",
        "recoverable",
        "marks resources for recreation on the next apply",
    ),
    R(
        "IAC-WORKSPACE",
        "terraform tofu",
        r"^workspace\s+delete",
        45,
        "account",
        "irreversible",
        "deletes a workspace and its state pointer",
    ),
    # --- cloud CLIs ---------------------------------------------------------
    R(
        "AWS-READ",
        "aws",
        r"^\S+\s+(ls|describe|list|get|head|lookup|search|estimate|preview|"
        r"validate|simulate|test|generate|wait|check)[\w-]*",
        0,
        "none",
        "reversible",
        "read-only AWS API call",
        generic=True,
    ),
    R(
        "AWS-WRITE",
        "aws",
        r"^\S+\s+(create|put|update|modify|attach|associate|register|enable|"
        r"tag|set|import|copy|start|run|invoke|publish|authorize|grant|"
        r"allow|share|add)[\w-]*",
        30,
        "account",
        "recoverable",
        "mutates cloud state and may cost money immediately",
        generic=True,
    ),
    R(
        "AWS-DESTROY",
        "aws",
        r"^\S+\s+(delete|terminate|remove|destroy|deregister|detach|disable|"
        r"revoke|purge|release|cancel|abort|reboot|stop)[\w-]*",
        65,
        "account",
        "irreversible",
        "destructive AWS API call",
        "confirm the account and region on the profile you are about to use",
        generic=True,
    ),
    R(
        "AWS-S3-RB",
        "aws",
        r"^s3\s+rb\b|^s3api\s+delete-bucket",
        75,
        "account",
        "irreversible",
        "deletes a bucket; the name is then claimable by anyone and links 404 forever",
    ),
    R(
        "AWS-S3-RM-R",
        "aws",
        r"^s3\s+rm\b.*--recursive",
        80,
        "account",
        "irreversible",
        "recursive object delete: without versioning there is nothing to restore from",
        "`--dryrun` prints the exact key list it would delete",
    ),
    R(
        "AWS-EC2-TERM",
        "aws",
        r"^ec2\s+terminate-instances",
        80,
        "account",
        "irreversible",
        "terminates instances; instance-store data and the instance itself are gone",
    ),
    R(
        "AWS-RDS-DEL",
        "aws",
        r"^rds\s+delete-db-(instance|cluster)",
        85,
        "account",
        "irreversible",
        "deletes a database",
        "never with `--skip-final-snapshot`; take the final snapshot",
    ),
    R(
        "AWS-CFN-DEL",
        "aws",
        r"^cloudformation\s+delete-stack",
        80,
        "account",
        "irreversible",
        "deletes every resource the stack owns",
    ),
    R(
        "AWS-KMS-DEL",
        "aws",
        r"^kms\s+(schedule-key-deletion|disable-key)",
        85,
        "account",
        "irreversible",
        "without the key, every ciphertext under it is permanently unreadable",
    ),
    R(
        "AWS-IAM-DEL",
        "aws",
        r"^iam\s+(delete|detach|remove|update-assume-role-policy)",
        70,
        "account",
        "recoverable",
        "IAM changes can lock you (or every workload) out of the account",
        "check `iam simulate-principal-policy` and keep a break-glass admin session open",
    ),
    R(
        "AWS-ORG",
        "aws",
        r"^organizations\s+(leave|remove-account|delete|close-account)",
        90,
        "account",
        "irreversible",
        "organization-level change affecting whole accounts",
    ),
    R(
        "GCP-READ",
        "gcloud gsutil bq",
        r"^(\S+\s+)*(list|describe|get|ls|cat|show|info|version)\b",
        0,
        "none",
        "reversible",
        "read-only GCP call",
        generic=True,
    ),
    R(
        "GCP-DESTROY",
        "gcloud gsutil bq",
        r"^(\S+\s+)*(delete|destroy|remove|rm|rb|disable|revoke)\b",
        65,
        "account",
        "irreversible",
        "destructive GCP call",
        generic=True,
    ),
    R(
        "GCP-WRITE",
        "gcloud gsutil bq",
        r"^(\S+\s+){0,3}(create|add|update|set|enable|deploy|import|cp|mv|apply|attach)\b",
        30,
        "account",
        "recoverable",
        "creates or mutates GCP resources, and may start billing",
        generic=True,
    ),
    R(
        "GCP-PROJECT",
        "gcloud",
        r"^projects\s+delete",
        90,
        "account",
        "irreversible",
        "deletes a project and everything in it",
    ),
    R(
        "AZ-READ",
        "az",
        r"^(\S+\s+)*(list|show|get|check|version)\b",
        0,
        "none",
        "reversible",
        "read-only Azure call",
        generic=True,
    ),
    R(
        "AZ-DESTROY",
        "az",
        r"^(\S+\s+)*(delete|remove|purge|disable|revoke)\b",
        65,
        "account",
        "irreversible",
        "destructive Azure call",
        generic=True,
    ),
    R(
        "AZ-WRITE",
        "az",
        r"^(\S+\s+){0,3}(create|add|update|set|enable|deploy|import|start|restart)\b",
        30,
        "account",
        "recoverable",
        "creates or mutates Azure resources, and may start billing",
        generic=True,
    ),
    R(
        "AZ-GROUP-DEL",
        "az",
        r"^group\s+delete",
        85,
        "account",
        "irreversible",
        "deletes a resource group: everything inside it goes, asynchronously and silently",
    ),
    # --- databases ----------------------------------------------------------
    R(
        "DB-CLIENT",
        "psql mysql mariadb mongo mongosh redis-cli sqlite3 clickhouse-client",
        None,
        15,
        "host",
        "recoverable",
        "database client session",
    ),
    R(
        "DB-DROP",
        "psql mysql mariadb sqlite3 clickhouse-client",
        r"\bDROP\s+(TABLE|INDEX|VIEW|SEQUENCE)\b",
        78,
        "account",
        "irreversible",
        "DROP is instant and unlogged in most setups: restore-from-backup is the only undo",
        "take a dump first; wrap it in BEGIN/ROLLBACK to see what it touches",
    ),
    R(
        "DB-DROP-DB",
        "psql mysql mariadb sqlite3 clickhouse-client",
        r"\bDROP\s+(DATABASE|SCHEMA)\b",
        88,
        "account",
        "irreversible",
        "drops an entire database: every table, index and grant in it",
        "restore-testing your backup is cheaper than discovering it does not restore",
    ),
    R(
        "DB-TRUNCATE",
        "psql mysql mariadb sqlite3",
        r"\bTRUNCATE\b",
        70,
        "account",
        "irreversible",
        "TRUNCATE empties the table and usually skips triggers and the redo path",
    ),
    R(
        "DB-DELETE-ALL",
        "psql mysql mariadb sqlite3",
        r"\bDELETE\s+FROM\s+[\w.\"`]+\s*(;|$|\")",
        75,
        "account",
        "irreversible",
        "DELETE with no WHERE clause: every row",
        "run it as `SELECT count(*)` first, then add the WHERE",
    ),
    R(
        "DB-UPDATE-ALL",
        "psql mysql mariadb sqlite3",
        r"\bUPDATE\s+[\w.\"`]+\s+SET\b(?!.*\bWHERE\b)",
        65,
        "account",
        "irreversible",
        "UPDATE with no WHERE clause: every row",
    ),
    R(
        "DB-DROP-COLUMN",
        "psql mysql mariadb sqlite3",
        r"\bALTER\s+TABLE\b.*\bDROP\s+(COLUMN|CONSTRAINT)\b",
        70,
        "account",
        "irreversible",
        "dropping a column deletes its data; no migration framework can bring it back",
    ),
    R(
        "DB-GRANT",
        "psql mysql mariadb",
        r"\b(GRANT|REVOKE|ALTER\s+USER|DROP\s+USER)\b",
        45,
        "account",
        "recoverable",
        "changes database access control",
    ),
    R(
        "DB-FLUSH",
        "redis-cli",
        r"\bFLUSH(ALL|DB)\b",
        85,
        "account",
        "irreversible",
        "empties the keyspace; if this is a cache in front of a cold DB, it is also an outage",
    ),
    R(
        "DB-MONGO-DROP",
        "mongo mongosh",
        r"\bdrop(Database|Collection)?\s*\(",
        88,
        "account",
        "irreversible",
        "drops a Mongo database or collection",
    ),
    R(
        "DB-RESTORE",
        "pg_restore mysqlimport mongorestore",
        r"--drop|--clean",
        60,
        "account",
        "irreversible",
        "restore with --clean/--drop removes existing objects before loading",
    ),
    # --- exposure: widening access is a different failure from destroying ----
    R(
        "SEC-IAM-KEY",
        "aws",
        r"^iam\s+create-access-key",
        50,
        "account",
        "recoverable",
        "mints a long-lived access key: it does not expire, it will end up in a file, and it "
        "carries everything that user can do",
        "prefer a role with short-lived credentials; if you must, record the key id to rotate",
    ),
    R(
        "SEC-S3-PUBLIC",
        "aws",
        r"(put-bucket-acl|put-object-acl).*(public-read|public-read-write)|"
        r"delete-public-access-block|"
        r"put-public-access-block.*BlockPublicAcls=false",
        70,
        "account",
        "recoverable",
        "makes bucket contents world-readable — this is the classic data leak",
        "check what is in the bucket before, not after",
    ),
    R(
        "SEC-IAM-ADMIN",
        "aws",
        r"(attach|put)-(role|user|group)-policy.*"
        r"(AdministratorAccess|PowerUserAccess)",
        70,
        "account",
        "recoverable",
        "grants administrator rights: whoever holds that principal now owns the account",
    ),
    R(
        "SEC-GCP-ALLUSERS",
        "gcloud gsutil",
        r"(allUsers|allAuthenticatedUsers)",
        70,
        "account",
        "recoverable",
        "`allUsers` means the public internet, unauthenticated",
    ),
    R(
        "SEC-K8S-ADMIN",
        "kubectl oc",
        r"create\s+clusterrolebinding.*(cluster-admin|--user=system:anonymous)|"
        r"create\s+clusterrolebinding.*--group=system:unauthenticated",
        70,
        "cluster",
        "recoverable",
        "binds cluster-admin: this is full control of every workload and secret",
    ),
    R(
        "SEC-SELINUX",
        "setenforce aa-disable",
        None,
        45,
        "host",
        "reversible",
        "disables mandatory access control for the whole host",
    ),
    R(
        "SEC-AUDIT",
        "auditctl",
        r"(^|\s)-D(\s|$)|-e\s+0",
        60,
        "host",
        "irreversible",
        "deletes every audit rule: the host stops recording what happens next",
    ),
    R(
        "SEC-JOURNAL",
        "journalctl",
        r"--vacuum-(time|size|files)|--rotate",
        45,
        "host",
        "irreversible",
        "truncates the journal: the evidence of what happened goes with it",
    ),
    # --- storage, devices, virtualisation ------------------------------------
    R(
        "FS-DISCARD",
        "blkdiscard nvme hdparm sg_format",
        r"^(format|--security-erase|"
        r"--security-erase-enhanced|--trim-sector-ranges)|^/dev/",
        90,
        "host",
        "irreversible",
        "issues a device-level erase: the controller drops the mapping, so no undelete exists",
        "there is no recovery path for this one — verify the device node twice",
    ),
    R(
        "FS-CRYPT",
        "cryptsetup",
        r"^(luksFormat|erase|luksErase|luksRemoveKey|luksKillSlot)",
        90,
        "host",
        "irreversible",
        "destroys or rewrites the LUKS header; without it the data is unrecoverable even with the right passphrase",
        "`cryptsetup luksHeaderBackup` first, always",
    ),
    R(
        "FS-BADBLOCKS",
        "badblocks",
        r"(^|\s)-w",
        85,
        "host",
        "irreversible",
        "`-w` is the destructive write test: it overwrites every block it checks",
    ),
    R(
        "FS-ZPOOL",
        "zpool",
        r"^(destroy|labelclear|remove|split)",
        85,
        "host",
        "irreversible",
        "destroys a pool or clears its labels; every dataset on it goes",
    ),
    R(
        "FS-FSCK",
        "fsck e2fsck xfs_repair",
        r"(^|\s)-[ypfL]|(^|\s)-a\b",
        55,
        "host",
        "recoverable",
        "auto-repair discards what it cannot reconcile; `xfs_repair -L` zeroes the log and its unflushed writes",
        "image the filesystem first if the data is worth more than the downtime",
        subsumes="ASSUME-YES",
    ),
    R(
        "FS-RESIZE",
        "resize2fs lvreduce xfs_growfs",
        r"(^|\s)-[LrR]\b|\b\d+[KMGTPkmgtp]?(\s|$)|--size",
        70,
        "host",
        "irreversible",
        "shrinking a filesystem or volume below its used size truncates data",
    ),
    R(
        "FS-MDADM",
        "mdadm",
        r"--(zero-superblock|fail|remove|stop|create)",
        80,
        "host",
        "irreversible",
        "changes RAID membership; zeroing a superblock forgets the array layout",
    ),
    R("SYS-SYSRQ", "", None, 0, "none", "reversible", "placeholder"),
    # --- boot path: the host comes back, or it does not ----------------------
    R(
        "BOOT-LOADER",
        "grub-install update-grub grub2-mkconfig grub2-install dracut mkinitcpio update-initramfs efibootmgr bootctl",
        None,
        60,
        "host",
        "recoverable",
        "rewrites the boot path; a mistake here is not visible until the next reboot, and the "
        "fix needs console or rescue media",
        "keep the previous kernel entry, and reboot while you still have console access",
    ),
    R(
        "BOOT-TUNE2FS",
        "tune2fs",
        r"-U|-L|-O",
        65,
        "host",
        "recoverable",
        "changing a filesystem UUID or label breaks every fstab entry and bootloader stanza "
        "that referenced the old one",
    ),
    R(
        "BOOT-KEXEC",
        "kexec",
        r"-e|--exec",
        70,
        "host",
        "recoverable",
        "switches to another kernel immediately, without firmware or a clean shutdown",
    ),
    R(
        "BOOT-MODULE",
        "rmmod modprobe insmod",
        r"^(-r|--remove)|^\w",
        45,
        "host",
        "recoverable",
        "unloading a kernel module can remove the storage or network driver the host is using",
    ),
    R(
        "SYS-TIME",
        "timedatectl ntpdate chronyc hwclock",
        r"set-time|set-timezone|makestep|-w|--systohc|^\S+\.",
        40,
        "host",
        "recoverable",
        "a clock jump invalidates TLS sessions, tokens and TOTP, and confuses anything that "
        "reasons about ordering (replication, leases, certificates)",
    ),
    # --- keys and certificates ----------------------------------------------
    R(
        "CERT-REVOKE",
        "certbot acme.sh lego",
        r"^(revoke|delete)\b|--revoke",
        70,
        "network",
        "irreversible",
        "revoking a certificate breaks TLS for every client that checks revocation, "
        "immediately and irreversibly — reissue is a new certificate, not an undo",
    ),
    R(
        "KEY-DELETE",
        "gpg keytool ssh-keygen",
        r"--delete-secret|--delete-key|-delete\b|--remove-key",
        75,
        "account",
        "irreversible",
        "deleting a private key destroys access to everything encrypted or signed with it",
    ),
    # --- cluster membership --------------------------------------------------
    R(
        "CLUSTER-RESET",
        "kubeadm k3s-uninstall.sh k0s",
        r"^reset\b|^uninstall\b|^stop\b",
        85,
        "cluster",
        "irreversible",
        "resets the node out of the cluster: certificates, etcd member and CNI state are all removed",
        "on a control-plane node this can lose quorum for the whole cluster",
    ),
    R(
        "CLUSTER-LEAVE",
        "docker consul nomad",
        r"^swarm\s+leave|^leave\b|^(server|node)\s+force-leave",
        60,
        "cluster",
        "recoverable",
        "removes this node from its cluster",
    ),
    R(
        "ETCD-RESTORE",
        "etcdctl etcdutl",
        r"snapshot\s+restore",
        80,
        "cluster",
        "irreversible",
        "restoring a snapshot replaces current cluster state with the snapshot's: everything "
        "written since it was taken is gone",
    ),
    # --- data services -------------------------------------------------------
    R(
        "MQ-RESET",
        "rabbitmqctl",
        r"^(reset|force_reset|purge_queue|delete_queue|delete_vhost)",
        75,
        "account",
        "irreversible",
        "resets the broker or empties a queue: in-flight messages have no other copy",
    ),
    R(
        "KAFKA-DELETE",
        "kafka-topics.sh kafka-topics kafka-configs.sh",
        r"--delete\b",
        75,
        "account",
        "irreversible",
        "deleting a topic drops its partitions and every retained message",
    ),
    R(
        "PG-RESET",
        "pg_resetwal pg_resetxlog",
        None,
        90,
        "account",
        "irreversible",
        "resetting the write-ahead log discards unreplayed transactions and can leave the "
        "cluster silently inconsistent",
        "this is a last resort after hardware failure, not a startup fix — take a file-level "
        "copy of the data directory first",
    ),
    R(
        "PG-STOP-IMMEDIATE",
        "pg_ctl",
        r"stop\b.*-m\s*(immediate|i)\b",
        55,
        "host",
        "recoverable",
        "immediate mode aborts every session without a checkpoint: recovery runs on next start",
    ),
    R(
        "MYSQLADMIN",
        "mysqladmin",
        r"^(drop|shutdown|flush-logs|reset)",
        70,
        "account",
        "irreversible",
        "drops a database or stops the server without a graceful shutdown",
    ),
    # --- schema migrations ---------------------------------------------------
    R(
        "MIGRATE-CLEAN",
        "flyway liquibase",
        r"^(clean|dropAll|drop-all)\b",
        90,
        "account",
        "irreversible",
        "drops every object in the target schema — this is the command Flyway ships a "
        "`cleanDisabled` setting for, because it has erased production before",
    ),
    R(
        "MIGRATE-RESET",
        "rails rake bin/rails",
        r"db:(drop|reset|purge)\b",
        85,
        "account",
        "irreversible",
        "drops the application database",
    ),
    R(
        "MIGRATE-DJANGO",
        "django-admin manage.py python",
        r"(manage\.py\s+)?(flush|sqlflush)\b",
        70,
        "account",
        "irreversible",
        "`flush` deletes every row in every table",
    ),
    R(
        "MIGRATE-PRISMA",
        "prisma npx",
        r"migrate\s+reset\b",
        80,
        "account",
        "irreversible",
        "drops and recreates the database from migrations: all data goes",
    ),
    R(
        "MIGRATE-DOWN",
        "alembic knex sequelize goose dbmate",
        r"downgrade\s+base|migrate:rollback.*--all|down-to\s+0|^down\b",
        70,
        "account",
        "irreversible",
        "rolls every migration back to an empty schema",
    ),
    # --- network plumbing ----------------------------------------------------
    R(
        "NET-CONNTRACK",
        "conntrack",
        r"(^|\s)-F(\s|$)|--flush",
        45,
        "network",
        "recoverable",
        "flushing connection tracking drops every NAT mapping: established connections through "
        "this host break mid-stream",
    ),
    R(
        "NET-NETNS",
        "ip",
        r"^netns\s+(del|delete)",
        50,
        "network",
        "recoverable",
        "deleting a network namespace takes its interfaces and the workloads using them",
    ),
    R(
        "NET-BRIDGE",
        "ovs-vsctl brctl",
        r"^(del-br|delbr|del-port|delif|emer-reset)",
        55,
        "network",
        "recoverable",
        "removing a bridge disconnects every interface attached to it — on a hypervisor that is every guest",
    ),
    # --- macOS ---------------------------------------------------------------
    R(
        "MAC-DISKUTIL",
        "diskutil",
        r"^(eraseDisk|eraseVolume|reformat|apfs\s+delete|"
        r"apfs\s+deleteContainer|zeroDisk|secureErase)",
        90,
        "host",
        "irreversible",
        "erases or reformats a volume",
    ),
    # --- config management --------------------------------------------------
    # --- the long tail: any CLI that manages remote resources -----------------
    # Verb classification, so a CLI nobody wrote a rule for is still scored.
    R(
        "CLI-READ",
        RESOURCE_CLIS,
        READ_VERBS,
        0,
        "none",
        "reversible",
        "read-only query against a managed resource",
        generic=True,
    ),
    R(
        "CLI-WRITE",
        RESOURCE_CLIS,
        WRITE_VERBS,
        25,
        "account",
        "recoverable",
        "creates or mutates a managed resource, and may start billing",
        generic=True,
    ),
    R(
        "CLI-DESTROY",
        RESOURCE_CLIS,
        DESTROY_VERBS,
        65,
        "account",
        "irreversible",
        "destructive verb against a managed resource",
        "confirm the profile/project/zone this CLI is pointed at before it runs",
        generic=True,
    ),
    # --- CLIs whose verbs do not mean what the generic rules assume ----------
    R(
        "VIRSH-DESTROY",
        "virsh",
        r"^destroy\b",
        45,
        "host",
        "recoverable",
        "`virsh destroy` force-powers-off a domain — it does not delete it; the disk survives",
    ),
    R(
        "VIRSH-UNDEFINE",
        "virsh",
        r"^(undefine|vol-delete|pool-delete|snapshot-delete)\b",
        70,
        "host",
        "irreversible",
        "removes the domain/volume definition and, with --remove-all-storage, its disks",
    ),
    R(
        "RCLONE-SYNC",
        "rclone",
        r"^(sync|move)\b",
        55,
        "account",
        "irreversible",
        "`rclone sync` makes the destination match the source: files only at the destination are deleted",
        "`--dry-run` first, and prefer `copy` when nothing should be removed",
    ),
    R(
        "RCLONE-PURGE",
        "rclone",
        r"^(purge|delete|deletefile|rmdir|rmdirs)\b",
        70,
        "account",
        "irreversible",
        "removes objects at the remote",
    ),
    R(
        "RESTIC-FORGET",
        "restic borg borgmatic",
        r"(forget|prune|delete)",
        65,
        "account",
        "irreversible",
        "drops snapshots from the backup repository — this is the copy you keep for when the primary is already gone",
        "`restic forget --dry-run`, and keep a retention policy rather than ad-hoc forgets",
    ),
    R(
        "ETCDCTL-DEL",
        "etcdctl",
        r"\bdel\b.*--prefix|--prefix.*\bdel\b",
        90,
        "cluster",
        "irreversible",
        "prefix delete against etcd: for a Kubernetes cluster this is the entire API state",
    ),
    R(
        "PULUMI-DESTROY",
        "pulumi",
        r"^(destroy|stack\s+rm)\b",
        80,
        "account",
        "irreversible",
        "tears down every resource in the stack",
    ),
    R(
        "PULUMI-UP",
        "pulumi",
        r"^(up|refresh|import)\b",
        45,
        "account",
        "recoverable",
        "applies stack changes to real infrastructure",
    ),
    R(
        "EKSCTL-DEL",
        "eksctl",
        r"^delete\s+cluster",
        85,
        "account",
        "irreversible",
        "deletes the cluster and the CloudFormation stacks behind it",
    ),
    R(
        "HEROKU-DESTROY",
        "heroku",
        r"(apps:destroy|pg:reset|addons:destroy)",
        85,
        "account",
        "irreversible",
        "destroys the app or resets the database, add-on data included",
    ),
    R(
        "ZFS-DESTROY",
        "zfs btrfs",
        r"^(destroy|delete|subvolume delete)\b",
        80,
        "host",
        "irreversible",
        "destroys a dataset, subvolume or snapshot",
        "`zfs destroy -n -v` prints what would go, snapshots included",
    ),
    R(
        "LVM-REMOVE",
        "lvremove vgremove pvremove mdadm",
        r"",
        80,
        "host",
        "irreversible",
        "removes a logical volume, volume group or RAID superblock: the data on it is gone",
    ),
    R(
        "CEPH-DEL",
        "ceph rbd",
        r"(purge|pool\s+(delete|rm)|rm\b|osd\s+destroy)",
        80,
        "cluster",
        "irreversible",
        "destructive Ceph operation against pooled storage",
    ),
    R(
        "SNAP-REMOVE",
        "snap flatpak",
        r"^(remove|uninstall)\b",
        45,
        "host",
        "recoverable",
        "removing a snap deletes the application's data unless a snapshot is kept",
    ),
    R(
        "NOMAD-PURGE",
        "nomad",
        r"^job\s+stop\b.*-purge",
        55,
        "cluster",
        "irreversible",
        "purges the job from state, not just its allocations",
    ),
    R(
        "S3CMD-RB",
        "s3cmd",
        r"^(rb|del|rm)\b",
        65,
        "account",
        "irreversible",
        "removes objects or a bucket",
    ),
    # --- promoted CLIs: enumerated per resource, not classified by verb -----
    #
    # Verb classification is a floor, not a measurement: it cannot see that
    # `openstack volume delete` costs data and `openstack server stop` costs a
    # reboot, and it cannot see the verbs that lie. These six carry the traffic
    # and the blast radius, so they are enumerated. Everything else in
    # RESOURCE_CLIS is still classified — see the CLI-* rules above.
    # vault ------------------------------------------------------------------
    R(
        "VAULT-READ",
        "vault",
        r"^(read|kv\s+get)\b",
        15,
        "account",
        "reversible",
        "prints a secret to stdout: from here it is in the scrollback, in the CI log if this "
        "runs in one, and in whatever consumed it — Vault records the read, it cannot unsend it",
        "`-field=<key>` prints one value instead of the whole secret, and a short-lived dynamic "
        "credential beats reading a static one",
    ),
    R(
        "VAULT-KV-DELETE",
        "vault",
        r"^kv\s+delete\b",
        35,
        "account",
        "recoverable",
        "`kv delete` is a soft delete: the versions are marked deleted and stay in storage — it "
        "is `kv destroy` and `kv metadata delete` that are permanent",
        "`vault kv undelete -versions=N <path>` brings it back",
    ),
    R(
        "VAULT-KV-DESTROY",
        "vault",
        r"^kv\s+(destroy|metadata\s+delete)\b",
        70,
        "account",
        "irreversible",
        "removes the version data itself; `kv undelete` cannot bring it back, and "
        "`kv metadata delete` takes every version and the metadata with them",
        "`vault kv delete` is the soft form and is recoverable",
    ),
    R(
        "VAULT-SECRETS-DISABLE",
        "vault",
        r"^secrets\s+disable\b",
        80,
        "account",
        "irreversible",
        "disabling a secrets mount deletes every secret stored under it, not just the route to them",
        "`vault secrets move` relocates a mount without emptying it",
    ),
    R(
        "VAULT-AUTH-DISABLE",
        "vault",
        r"^auth\s+disable\b",
        75,
        "account",
        "irreversible",
        "disabling an auth method revokes every token it issued: every client that authenticates "
        "this way is locked out at once, including the one running this",
        "`vault list auth/<path>/role` shows what still comes in through it",
    ),
    R(
        "VAULT-AUDIT-DISABLE",
        "vault",
        r"^audit\s+disable\b",
        60,
        "account",
        "irreversible",
        "Vault stops recording who read which secret, and keeps serving requests while it does "
        "— the gap in the audit trail is silent",
        "enable the replacement device first; Vault only refuses requests when *every* audit device fails",
    ),
    R(
        "VAULT-LEASE-REVOKE",
        "vault",
        r"^lease\s+revoke\b",
        65,
        "account",
        "irreversible",
        "revokes leases and the credentials behind them: the database users and cloud keys "
        "Vault issued are dropped as it goes",
        "`vault list sys/leases/lookup/<prefix>` first — it prints exactly what would be revoked",
    ),
    R(
        "VAULT-TOKEN-REVOKE",
        "vault",
        r"^token\s+revoke\b",
        45,
        "account",
        "irreversible",
        "a token revoke takes its child tokens too, so revoking a parent ends every session issued from it",
    ),
    R(
        "VAULT-POLICY-DELETE",
        "vault",
        r"^policy\s+delete\b",
        55,
        "account",
        "recoverable",
        "every token and role bound to this policy loses the access it granted, immediately and "
        "with no error here — it shows up as permission denied somewhere else",
        "`vault policy read <name>` and keep the HCL before deleting it",
    ),
    R(
        "VAULT-SEAL",
        "vault",
        r"^operator\s+(seal|step-down)\b",
        60,
        "cluster",
        "recoverable",
        "sealing Vault stops every client that needs a secret until enough key holders unseal it "
        "again — which needs the people, not just the command",
    ),
    R(
        "VAULT-REKEY",
        "vault",
        r"^operator\s+(rekey|generate-root|rotate)\b",
        70,
        "cluster",
        "irreversible",
        "rekeying invalidates the existing unseal shares: the old ones stop working the moment "
        "it completes, and losing the new ones loses the cluster",
    ),
    R(
        "VAULT-RAFT-RESTORE",
        "vault",
        r"^operator\s+raft\s+snapshot\s+restore\b",
        90,
        "cluster",
        "irreversible",
        "replaces the whole of Vault's storage with the snapshot: every secret, policy, mount and "
        "token written since it was taken is gone",
        "take a fresh snapshot first — this is the one operation with no other way back",
    ),
    R(
        "VAULT-RAFT-PEER",
        "vault",
        r"^operator\s+raft\s+remove-peer\b",
        65,
        "cluster",
        "recoverable",
        "shrinks the raft quorum; one peer too many and the cluster loses quorum and stops serving entirely",
    ),
    # velero -----------------------------------------------------------------
    R(
        "VELERO-BACKUP-CREATE",
        "velero",
        r"^backup\s+create\b",
        10,
        "cluster",
        "reversible",
        "takes a backup: the cost is load on the cluster and object storage, not data",
    ),
    R(
        "VELERO-BACKUP-DELETE",
        "velero",
        r"^backup\s+delete\b",
        70,
        "cluster",
        "irreversible",
        "deletes the backup and the objects behind it in storage: that point in time stops being "
        "restorable, and you find out at the restore",
        "`velero backup describe <name>` — check something newer covers the same namespaces",
    ),
    R(
        "VELERO-RESTORE-DELETE",
        "velero",
        r"^restore\s+delete\b",
        35,
        "cluster",
        "recoverable",
        "deletes the restore *record*, not what it restored — the objects it created stay in the "
        "cluster, now with nothing describing where they came from",
    ),
    R(
        "VELERO-RESTORE-CREATE",
        "velero",
        r"^restore\s+create\b",
        50,
        "cluster",
        "irreversible",
        "a restore writes into a live cluster: existing objects are skipped by default, but the "
        "ones it does create are hard to tell apart from what was already there afterwards",
        "`--namespace-mappings old:scratch` restores into a scratch namespace you can inspect",
    ),
    R(
        "VELERO-SCHEDULE",
        "velero",
        r"^schedule\s+(delete|pause)\b",
        55,
        "cluster",
        "recoverable",
        "nothing breaks today: backups simply stop being taken, and the cost lands at the next restore instead",
        "`velero schedule get` to confirm what else still covers these namespaces",
    ),
    R(
        "VELERO-LOCATION-DELETE",
        "velero",
        r"^(backup-location|snapshot-location)\s+delete\b",
        65,
        "cluster",
        "irreversible",
        "removes the storage location: every backup that lives there stops being visible to "
        "Velero, whether or not the bucket still holds it",
    ),
    R(
        "VELERO-UNINSTALL",
        "velero",
        r"^uninstall\b",
        75,
        "cluster",
        "irreversible",
        "removes Velero and its CRDs — the Backup and Restore objects describing every existing "
        "backup go with them, leaving data in the bucket with nothing that can read it",
        "keep the backup storage location and its bucket; a reinstall can re-sync from it",
    ),
    # argocd -----------------------------------------------------------------
    R(
        "ARGOCD-APP-DELETE",
        "argocd",
        r"^app\s+delete\b",
        60,
        "cluster",
        "irreversible",
        "deleting an application cascades by default: the Kubernetes resources it manages are deleted with it",
        "`--cascade=false` removes the Argo CD record and leaves the workloads running",
    ),
    R(
        "ARGOCD-APP-SYNC",
        "argocd",
        r"^app\s+sync\b",
        40,
        "cluster",
        "recoverable",
        "applies whatever is in git to the cluster right now — including a commit nobody has "
        "reviewed yet, because sync does not care why HEAD moved",
        "`argocd app diff` prints what would change, and `--dry-run` runs it without applying",
        subsumes="PURGE-FLAG FORCE",
    ),
    R(
        "ARGOCD-PROJ-DELETE",
        "argocd",
        r"^(proj|project)\s+delete\b",
        70,
        "cluster",
        "irreversible",
        "deleting a project takes every application in it, and each of those cascades to its own cluster resources",
    ),
    R(
        "ARGOCD-CLUSTER-RM",
        "argocd",
        r"^cluster\s+rm\b",
        45,
        "cluster",
        "recoverable",
        "`cluster rm` de-registers the cluster from Argo CD — it does not touch the cluster. The "
        "applications targeting it stop being reconciled and drift silently from here",
        "`argocd app list --dest-server <url>` shows what stops being managed",
    ),
    R(
        "ARGOCD-REPO-RM",
        "argocd",
        r"^repo\s+rm\b",
        40,
        "cluster",
        "recoverable",
        "removes the repository credentials: every application sourced from it fails to refresh, "
        "with no change to what is already running",
    ),
    R(
        "ARGOCD-ADMIN-IMPORT",
        "argocd",
        r"^admin\s+import\b",
        70,
        "cluster",
        "irreversible",
        "replaces Argo CD's stored state with the contents of the export: applications and "
        "projects that are not in the file are deleted",
        "`argocd admin export > backup.yaml` first",
    ),
    # openstack --------------------------------------------------------------
    R(
        "OS-SERVER-POWER",
        "openstack",
        r"^server\s+(stop|reboot|shelve|suspend|pause|rescue|unset)\b",
        30,
        "account",
        "recoverable",
        "stops or reboots the instance; the disk and the ports survive it",
    ),
    R(
        "OS-SERVER-DELETE",
        "openstack",
        r"^server\s+delete\b",
        70,
        "account",
        "irreversible",
        "deletes the instance and its ephemeral disk; a boot-from-volume instance keeps its root "
        "volume only if it was not created with delete-on-termination",
        "`openstack server shelve` frees the compute and keeps the instance",
    ),
    R(
        "OS-VOLUME-DELETE",
        "openstack",
        r"^volume\s+delete\b",
        80,
        "account",
        "irreversible",
        "the data on the volume goes with it, and `--force` deletes it even while an instance still has it attached",
        "`openstack volume snapshot create` first — the snapshot is the only way back",
    ),
    R(
        "OS-SNAPSHOT-DELETE",
        "openstack",
        r"^(backup|volume\s+snapshot|image\s+snapshot)\s+delete\b",
        65,
        "account",
        "irreversible",
        "removes a restore point for a volume that is still running",
    ),
    R(
        "OS-IMAGE-DELETE",
        "openstack",
        r"^image\s+delete\b",
        60,
        "account",
        "irreversible",
        "instances already running are unaffected; everything that rebuilds, autoscales or "
        "launches from this image fails from now on",
    ),
    R(
        "OS-PROJECT-DELETE",
        "openstack",
        r"^project\s+delete\b",
        60,
        "account",
        "irreversible",
        "deleting a project does not delete what is in it: the servers, volumes and floating IPs "
        "keep running and keep billing, with no project left to manage them through",
        "`openstack project purge --project <id>` removes the resources first — then delete it",
    ),
    R(
        "OS-PROJECT-PURGE",
        "openstack",
        r"^project\s+purge\b",
        88,
        "account",
        "irreversible",
        "deletes every resource the project owns — servers, volumes, images, networks — in one call",
        "`--dry-run` prints the list without touching any of it",
    ),
    R(
        "OS-STACK-DELETE",
        "openstack",
        r"^stack\s+delete\b",
        85,
        "account",
        "irreversible",
        "a Heat stack delete removes every resource the template created, database volumes included",
    ),
    R(
        "OS-NETWORK-DELETE",
        "openstack",
        r"^(network|subnet|router|port)\s+delete\b",
        70,
        "network",
        "irreversible",
        "removing the network takes the ports on it: every instance attached loses connectivity, "
        "and on a cloud you administer remotely this is how you lock yourself out",
    ),
    R(
        "OS-CATALOG-DELETE",
        "openstack",
        r"^(endpoint|service)\s+delete\b",
        75,
        "account",
        "irreversible",
        "the service catalog is how every client finds this region's APIs — removing an entry "
        "makes that service unreachable region-wide without touching anything it manages",
    ),
    R(
        "OS-USER-DELETE",
        "openstack",
        r"^(user|role|group)\s+delete\b",
        55,
        "account",
        "irreversible",
        "the tokens stop working immediately; resources the user owned keep running, now with "
        "nobody who can reach them",
    ),
    R(
        "OS-SG-RULE",
        "openstack",
        r"^security\s+group\s+rule\s+create\b",
        30,
        "network",
        "reversible",
        "opens a port to whatever `--remote-ip` names — the range is the whole of the decision",
        "name a CIDR you control; `0.0.0.0/0` is the entire internet",
    ),
    # flyctl -----------------------------------------------------------------
    R(
        "FLY-DEPLOY",
        "flyctl fly",
        r"^deploy\b",
        35,
        "account",
        "recoverable",
        "rolls the app forward to a new release",
        "`fly releases` lists what to roll back to, and `fly deploy --image <ref>` does it",
    ),
    R(
        "FLY-SECRETS",
        "flyctl fly",
        r"^secrets\s+(set|unset|import)\b",
        40,
        "account",
        "recoverable",
        "setting a secret restarts every machine in the app — this is a deploy, not a config "
        "write, and it happens the moment the command returns",
        "`--stage` stores the secret without restarting; the next deploy picks it up",
    ),
    R(
        "FLY-SCALE-ZERO",
        "flyctl fly",
        r"^scale\s+count\s+0\b",
        55,
        "account",
        "recoverable",
        "zero machines is an outage: nothing is deleted and scaling back up restores it, but the "
        "app is off until you do",
    ),
    R(
        "FLY-MACHINE-DESTROY",
        "flyctl fly",
        r"^machines?\s+(destroy|remove)\b",
        55,
        "account",
        "recoverable",
        "destroys one machine — the app, its volumes and its config survive, and `fly deploy` recreates it",
    ),
    R(
        "FLY-VOLUME-DESTROY",
        "flyctl fly",
        r"^volumes?\s+(destroy|delete)\b",
        85,
        "account",
        "irreversible",
        "a Fly volume is a single local disk, not a replicated one: this destroys the only copy of the data on it",
        "`fly volumes snapshots list <id>` — snapshots are kept about five days and are the only way back",
    ),
    R(
        "FLY-APPS-DESTROY",
        "flyctl fly",
        r"^apps\s+destroy\b",
        80,
        "account",
        "irreversible",
        "destroys the app with its machines and its volumes, and releases the name for anyone else to claim",
        "`fly scale count 0` stops it running and billing without destroying anything",
    ),
    R(
        "FLY-PG-DETACH",
        "flyctl fly",
        r"^(postgres|pg|mysql)\s+(detach|db\s+delete)\b",
        65,
        "account",
        "irreversible",
        "detaching drops the database user and removes DATABASE_URL from the app: the app loses "
        "its database at the next restart, not at this command",
    ),
    R(
        "FLY-CERTS-REMOVE",
        "flyctl fly",
        r"^certs\s+remove\b",
        45,
        "network",
        "recoverable",
        "removes the certificate for that hostname; requests to it stop being served over HTTPS "
        "until a new one is issued and validated",
    ),
    # gh ---------------------------------------------------------------------
    R(
        "GH-REPO-ARCHIVE",
        "gh",
        r"^repo\s+archive\b",
        20,
        "account",
        "recoverable",
        "makes the repository read-only and can be undone — the reversible alternative to `repo delete`",
    ),
    R(
        "GH-REPO-DEL",
        "gh",
        r"^repo\s+delete\b",
        75,
        "account",
        "irreversible",
        "deletes the repository with its issues, PRs and releases; the name is then claimable by anyone",
        "`gh repo archive` keeps it readable and reversible",
    ),
    R(
        "GH-PR-MERGE",
        "gh",
        r"^pr\s+merge\b",
        40,
        "account",
        "recoverable",
        "merges into the base branch — on a repository that deploys on merge, this is the deploy",
        "`--auto` waits for the required checks instead of merging now",
    ),
    R(
        "GH-RELEASE-DELETE",
        "gh",
        r"^release\s+delete\b",
        55,
        "account",
        "irreversible",
        "deletes the release and every asset attached to it: anything pinned to those download "
        "URLs breaks, including other people's CI",
        "`gh release edit <tag> --draft` hides it and keeps the assets",
    ),
    R(
        "GH-ISSUE-DELETE",
        "gh",
        r"^issue\s+delete\b",
        50,
        "account",
        "irreversible",
        "GitHub has no undo for a deleted issue: the thread, its comments and every cross-reference to it go",
        "closing it keeps the history and is reversible",
    ),
    R(
        "GH-RUN-DELETE",
        "gh",
        r"^(run\s+delete|cache\s+delete)\b",
        35,
        "account",
        "irreversible",
        "deletes the run and its logs — the record of what CI actually did is the thing being removed",
    ),
    R(
        "GH-SECRET",
        "gh",
        r"^(secret|variable)\s+(set|delete)\b",
        40,
        "account",
        "recoverable",
        "changes what every workflow in this repository runs with; `secret delete` cannot be "
        "undone without the original value, which by design nothing here can read back",
    ),
    R(
        "GH-WORKFLOW-RUN",
        "gh",
        r"^workflow\s+run\b",
        35,
        "account",
        "recoverable",
        "triggers a workflow: what it does is whatever the workflow does, which on a deploy pipeline is a deploy",
    ),
    R(
        "GH-AUTH-TOKEN",
        "gh",
        r"^auth\s+token\b",
        35,
        "account",
        "reversible",
        "prints the OAuth token to stdout, where it lands in scrollback and in the CI log if this runs in one",
        "let `gh` make the authenticated call instead of extracting the token",
    ),
    R(
        "GH-API-WRITE",
        "gh",
        r"^api\b(?=.*(?:-X|--method)[= ]?(?:POST|PUT|PATCH))",
        45,
        "account",
        "recoverable",
        "`gh api` is the raw REST API: the verb that matters is in `-X`, and nothing else on the "
        "command line says what this changes",
        "run it with `--method GET` first and read what the endpoint returns",
    ),
    R(
        "GH-API-DELETE",
        "gh",
        r"^api\b(?=.*(?:-X|--method)[= ]?DELETE)",
        70,
        "account",
        "irreversible",
        "a DELETE through `gh api` is whatever that endpoint deletes — `/repos/{owner}/{repo}` "
        "is the repository itself — and no verb in the command line says so",
        "check the endpoint in the REST docs; `gh` has a named command for most of the "
        "destructive ones, and those prompt",
    ),
    R(
        "CM-ANSIBLE",
        "ansible ansible-playbook",
        None,
        40,
        "cluster",
        "recoverable",
        "runs against every host in the inventory pattern at once",
        "`--check --diff` first, and `--limit` to one host before the fleet",
    ),
    R("CM-SALT", "salt", None, 45, "cluster", "recoverable", "runs across matched minions"),
]

SHELLS = {"sh", "bash", "zsh", "dash", "ksh"}
# Anything that turns bytes on stdin into a script: fetching and decoding are
# the same move when the next stage is an interpreter.
FETCHERS = {
    "curl",
    "wget",
    "fetch",
    "aria2c",
    "http",
    "httpie",
    "base64",
    "xxd",
    "openssl",
    "gunzip",
    "zcat",
    "gzip",
    "bunzip2",
    "xz",
}
INTERPRETERS = SHELLS | {"python", "python3", "perl", "ruby", "node", "php"}

